title: 'Obyte — a fully decentralized, DAG based crypto.'
default_lang: en
author:
  name: Obyte
  email: john@example.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Obyte is a neutral space for storing and moving value. It has no owners, like the air around us. It is decentralized, free of domination, free of censorship, and accessible to all. It is a ledger without middlemen. Block-free, miner-free, DAG based.'
  'og:description': 'Obyte is a neutral space for storing and moving value. It has no owners, like the air around us. It is decentralized, free of domination, free of censorship, and accessible to all. It is a ledger without middlemen. Block-free, miner-free, DAG based.'
  'og:type': website
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
acxtest: TEST
